# Generated by Django 4.1.1 on 2022-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretuser',
            old_name='child_drem',
            new_name='child_dream',
        ),
        migrations.RemoveField(
            model_name='secretuser',
            name='fool_dec',
        ),
        migrations.AddField(
            model_name='secretuser',
            name='fun_moment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='secretuser',
            name='job_desc',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
